# Playbook to get the Public DNS Name of EC2 and add it hosts file
# Created by: Arun Ghanta
# Date: 26/27th April 2017
# Depenedencies vars.yml outside the directory where this playbook is sitting
# Also using hosts.j2 jinja template

---
- hosts: control
  connection: local
  gather_facts: False
  vars_files:
  - ../vars.yml

  tasks:
    - name: Provision Instance/VM
      ec2_remote_facts:
         aws_access_key: "{{ access_key }}"
         aws_secret_key: "{{ secret_key }}"
         region: "{{ aws_region }}"
         filters:
          instance-state-name:  running
      register: ec2

    - debug:  var=ec2.instances[0].public_dns_name

    - template:
        src: ./hosts.j2
        dest: ./hosts
