---
- hosts: AWS
  gather_facts: yes
  become: yes
  remote_user: ec2-user
  connection: ssh
  vars_files:
  - ../vars.yml

  tasks:

    - name: install the nginx rpm from a remote repo
      yum:
        name: "{{ nginx_url }}"
        state: present

    - name: Copy Cooler
      copy: src=./cooler/ dest=/usr/share/nginx/html/ owner=root group=root mode=0644
      notify: nginx-reload

  handlers:
    - name: nginx-reload
      service: name=nginx state=restarted

