# Playbook to create an EC2 instance on AWS
# Created by: Arun Ghanta
# Date: 26/27th April 2017
# Depenedencies vars.yml outside the directory where this playbook is sitting
# Please execute ec2-info.yml after completion of this
# ec2-info.yml retrieves public dns name and adds it to hosts file for inventory purpose

---

- hosts: control
  connection: local
  gather_facts: False
  vars_files:
  - ../vars.yml

  tasks:
    - name: Provision Instance/VM
      ec2:
         aws_access_key: "{{ access_key }}"
         aws_secret_key: "{{ secret_key }}"
         region: "{{ aws_region }}"
         key_name: "{{ key_pair }}"
         instance_type: "{{ ec2_type }}"
         image: "{{ ami_id }}"
         instance_tags:
           Name: "{{ ec2_tag }}"
         exact_count: "{{ inst_count }}"
         count_tag:
           Name: "{{ cnt_tag }}"
         wait: yes
         vpc_subnet_id: "{{ subnet_id }}"
         assign_public_ip: yes
      register: ec2

    - name: SSH Availability
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: "{{ ec2.instances }}"

