# Playbook to install Nginx and Deploy sample web app
# Created by: Arun Ghanta
# Date: 26/27th April 2017
# Depenedencies vars.yml outside the directory where this playbook is sitting
# Also ansible-assignment.pem file with 600 mode perms
# Command to use this playbook:
#	 ansible-playbook --private-key=../ansible-assignment.pem ec2-webapp.yml

---
- hosts: AWS
  gather_facts: yes
  become: yes
  remote_user: ec2-user
  connection: ssh
  vars_files:
  - ../vars.yml

  tasks:

    - name: Install Nginx from Remote Repo
      yum:
        name: "{{ nginx_url }}"
        state: present
      tags:
         - Install_Nginx
 
    - name: Enable and start Nginx Service
      service:
        name: nginx
        state: started
        enabled: yes
      tags:
         - Start_Nginx_Service

    - name: Copy Cooler Webiste. Takes really really long time to copy
      copy: src=./cooler/ dest=/usr/share/nginx/html/ owner=root group=root mode=0644
      notify: nginx-reload
      tags:
         - Copy_Website

  handlers:
    - name: nginx-reload
      service: name=nginx state=restarted

