# Playbook to install Nginx and Deploy sample web app
# Created by: Arun Ghanta
# Date: 26/27th April 2017
# Depenedencies vars.yml outside the directory where this playbook is sitting
# Also ansible-assignment.pem file with 600 mode perms
# Command to use this playbook:
#	 ansible-playbook --private-key=../ansible-assignment.pem ec2-webapp.yml

---
- hosts: AWS
  gather_facts: yes
  become: yes
  remote_user: ec2-user
  connection: ssh
  vars_files:
  - ../vars.yml

  tasks:

    - name: install the nginx rpm from a remote repo
      yum:
        name: "{{ nginx_url }}"
        state: present

    - name: Copy Cooler
      copy: src=./cooler/ dest=/usr/share/nginx/html/ owner=root group=root mode=0644
      notify: nginx-reload

  handlers:
    - name: nginx-reload
      service: name=nginx state=restarted

